superfly/litefs

- db.go
- fuse/fuse.go
- fuse/fuse_test.go
This pull request blocks page writes that set the read & write file format versions to anything other than the rollback journal mode (`0x01`). This is a temporary fix until WAL support is enabled (#14).
Fixes #15
> Prevent WAL mode from being set

- cmd/litefs/main.go
- db.go
- fuse/database_node.go
- fuse/file_system.go
- fuse/fuse.go
- fuse/fuse_test.go
- fuse/journal_node.go
- fuse/primary_node.go
- fuse/root_node.go
- go.mod
- go.sum
- litefs.go
- store.go
After having issues on Fedora & Alpine (https://github.com/superfly/litefs/pull/31), I tried reworking the FUSE layer to use @tv42's `bazil.org/fuse` and it seems to be working better.
I need to hook in POSIX locks and fix up the test for the `TRUNCATE` journal mode as well but I'll do that in a separate PR.
> Replace hanwen/go-fuse with bazil.org/fuse

- .github/workflows/build_and_test.yml
- cmd/litefs/main_test.go
- db.go
- fuse/database_node.go
- fuse/file_system.go
- fuse/journal_node.go
- fuse/primary_node.go
- fuse/root_node.go
- litefs.go
This PR fixes the OS page cache invalidation on replica nodes by using `fs.Server.InvalidateNodeDataRange()` instead of `fuse.Conn.InvalidateEntry()`.
> Fix FUSE file invalidation

- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/main_test.go
- fuse/file_system_test.go
- store.go
- store_test.go
This pull request adds a `candidate` flag to the config which tells the node whether it can become the primary or not. It defaults to `true`.
Original PR: https://github.com/jwhear/litefs/pull/1
Fixes #16
> Implement candidacy

- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/main_test.go
- http/server.go
- lease.go
- lease_test.go
- litefs.go
- store.go
This adds support for a fixed primary node so that Consul does not need to be used. It will not support handoff of the primary so the cluster will be read-only when the primary stops.
Original PR: https://github.com/jwhear/litefs/pull/2
Fixes #37 
Specify the `static` block in your configuration instead of `consul`. You cannot specify both blocks.
```yml
static:
primary: true
primary-url: "http://myhost:20202"
```
```yml
static:
primary: false
primary-url: "http://myhost:20202"
```
> Implement static lease

- fuse/database_node.go
- fuse/journal_node.go
- fuse/primary_node.go
- fuse/root_node.go
Return ENOSYS for xattr requests so that they are permanently failed and no longer sent to the filesystem.
Relevant sources:
https://github.com/bazil/fuse/issues/254
https://github.com/libfuse/libfuse/blob/0b6d97cf5938f6b4885e487c3bd7b02144b1ea56/include/fuse_lowlevel.h#L811
> Return ENOSYS for xattr requests

- README.md
I'm opening up contributions for feature development after having a good experience working with @jwhear. The tl;dr is that feature implementations should be PR'd to your fork and then post a link in the relevant issue on this project. I work on features in a certain order so I'll pull in community implementations from the issue when I get to the feature.
I'm not sure if this is a good way to do things but I'm giving it a try. Feedback welcome!
> Update contribution policy

- fuse/file_system.go
- fuse/file_system_test.go
This pull request implements a FUSE callback for `statfs(2)`. The call is simply a passthrough to the underlying file system that the `litefs.Store` is attached to.
Fixes #10
> Implement statfs() callback

- db.go
- fuse/file_system.go
- fuse/file_system_test.go
- fuse/fuse.go
- fuse/pos_node.go
- fuse/root_node.go
- litefs.go
This pull request adds a "-pos" suffixed file for every database that will print out the database replication position (TXID + Checksum). This file is not listed when using `ls`. I don't have a strong opinion on that but it seems like it could add clutter to the `ls` output.
Original PR contributed by @jwhear: https://github.com/jwhear/litefs/pull/3
Fixes #42 
```sh
$ sqlite3 /mnt/db "CREATE TABLE t (x)"
$ cat /mnt/db-pos
0000000000000001/a33a614c099fbe7e
$ sqlite3 /mnt/db "INSERT INTO t VALUES (100)"
$ cat /mnt/db-pos
0000000000000002/e26f480a1d612519
```
> Expose DB position via FUSE

- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/main_test.go
- consul/consul.go
- fuse/primary_node.go
- fuse/root_node.go
- lease.go
- lease_test.go
- store.go
- store_test.go
Previously, the `.primary` file returns the advertise URL of the primary node. This is not terribly helpful for the replica node since they are not interested in contacting the LiteFS API.
This pull request changes the functionality so that `.primary` returns the hostname of the primary node. This can be set on the `static` lease by setting the `hostname` field. For Consul users, there is also a `hostname` field under `consul`, however, this field will default to the kernel's `hostname(1)` if unset.
The contents of the `.primary` file ends with a `\n` character so client applications should trim space before using.
```yml
static:
hostname: "myhost"
```
```yml
consul:
hostname: "myhost"
```
From a connected replica node:
```sh
$ cat /mnt/.primary
myhost
```
> Return hostname in primary file

- cmd/litefs/main.go
This allows `HOSTNAME` to be used in the configuration file variable expansion, even if it's unset by the environment.
> Set hostname env variable, if unset

- http/server.go
I'm not sure why I named it this way in the first place but now it's fixed. 👍
> Rename pprof import

- cmd/litefs/main.go
- db.go
- fuse/database_node.go
- fuse/file_system_test.go
- http/server.go
- rwmutex.go
- store.go
This pull request fixes lock handling by the FUSE layer. Previously I thought SQLite used OFD locks but it turns out that's not the case. This PR also includes the `GET /debug/vars` endpoint which is helpful to list out the internal state of the store & its databases.
> Fix database locks to use LockOwner

- db.go
- store.go
Previously, only the streamed LTX files to the replica were atomically written. This PR updates the FUSE commit path to also use atomic file writes (e.g. create temp, write, sync, rename, sync directory).
Fixes https://github.com/superfly/litefs/issues/77
> Atomically write LTX files on commit

- .github/workflows/build_and_test.yml
- .github/workflows/release.linux.yml
- Dockerfile
- db_test.go
- fuse/file_system_test.go
- go.mod
- http/server.go
- lease_test.go
- mock/client.go
- mock/lease.go
- store.go
- store_test.go
This pull request adds `Store.PrimaryCtx()` which wraps a `context.Context` and monitors for the loss of the primary state. This is hooked into `http.Server.serveStream()` so that connections will automatically disconnect when the primary status is lost.
Helps with https://github.com/superfly/litefs/pull/80
> Disconnect streams when primary status changes

- http/server.go
This pull request adds a nil check & a log if a replica connects and has a database that doesn't exist on the primary. This can occur because of a split brain situation since LiteFS replication is async. The primary is always the authority on the state of the store so a non-existent database is ignored. In the future, a message should be sent to the replica to delete the database.
Fixes https://github.com/superfly/litefs/issues/75
> Add DB nil check on HTTP server

- .github/workflows/release.docker.yml
- Dockerfile
- Makefile
The `GITHUB_TOKEN` was used when LiteFS was still a private repo. Now that it's public, it's no longer needed.
> Remove GITHUB_TOKEN & Makefile

- cmd/litefs/main.go
- http/server.go
This pull request adds a check to wait for the store to either become primary or connect to the primary before executing the subcommand (if set). Eventually it should wait until it is up to date with the primary (if connected as a replica) before proceeding.
> Wait for ready state on startup

- cmd/litefs/main_test.go
- db.go
- fuse/file_system.go
- store.go
This pull request simply adds a test to verify that a node will fail if there are invalid LTX files. Right now, manual intervention is needed to remedy this issue but, eventually, LiteFS should automatically recover.
> Ensure node does not startup if LTX files are invalid

- db.go
- fuse/file_system_test.go
- store.go
This pull request changes `ApplyLTX()` so it acquires exclusive locks on `RESERVED`, `SHARED`, & `PENDING` locks before applying. Locks will block until acquired or until the context is canceled. The `DB` mutex has also been moved so it is only held while the position is being updated.
> Fix locking on LTX apply

- db.go
- store.go
This pull request adds a check to ensure the DB position matches the min TXID & the pre-apply checksum in the LTX file header. This should already be handled by the HTTP server on the primary but this is an extra check to help ensure safety.
> Verify txid/checksum on LTX frame

- cmd/litefs/main.go
- cmd/litefs/main_test.go
- db.go
- fuse/file_system_test.go
- fuse/root_node.go
- store.go
This also adds a "StrictVerify" mode to the `Store` so that it re-computes the entire database checksum on every transaction. It's only intended to be used during testing.
> Fix LTX checksum on VACUUM

- cmd/litefs/main.go
- cmd/litefs/main_test.go
Previously, the `data-dir` was generated based on the path of the mount directory. However, this was confusing as persistent volumes need to be mounted to a directory with an explicit path so it's better to require `data-dir` to be explicit as well.
> Require explicit data directory

- .github/workflows/release.yml
Removing arm6 & arm7 builds until more testing can be done with them.
> Only release amd64 and arm64

- fuse/database_node.go
- fuse/shm_node.go
- fuse/wal_node.go
- rwmutex.go
- rwmutex_test.go
This PR fixes a bug in multi-process usage of SQLite when in WAL mode. Previously, running a read query while another process was open on the database would result in a `SQLITE_PROTOCOL` error. This was caused because LiteFS was not correctly setting the state of the blocking lock when `SHMNode.QueryLock()` was executed. Previously it was always returning `fuse.LockWrite` but SQLite needs to distinguish between a blocking read & write on the `UNIX_SHM_DMS` lock byte. SQLite executes a spin lock while this lock byte is under write lock and exit if it is has a read lock. Since it never showed the demotion of the write lock state to read lock state, this spin lock would eventually fail.
> Fix return lock type for SHM lock

- fuse/file_system_test.go
- fuse/root_node.go
- internal/testingutil/testingutil.go
Attempt to fix #124
After creating a db and set WAL journal mode, the mounted dir listing is:
```
$ ls dbs/ -lh
total 0
-rw-rw-rw- 1 daniel daniel 4.0K Oct 19 19:36 state.db
-rw-rw-rw- 1 daniel daniel  32K Oct 19 19:36 state.db-shm
-rw-rw-rw- 1 daniel daniel  37K Oct 19 19:36 state.db-wal
```
Passes tests:
```
$ go test -p 1 -timeout 5m ./fuse -journal-mode wal
ok      github.com/superfly/litefs/fuse 1.707s
$ go test -p 1 -timeout 5m ./fuse -journal-mode delete
ok      github.com/superfly/litefs/fuse 1.577s
```
> List journal filenames in root handle

- .github/workflows/docker_image.yml
- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
A bunch of improvements:
* Run the test suite on external contributions (PRs)
* Build docker image but don't push it unless it is on main repo
* Build and push docker image for main branch
* Update action versions to latest releases
* Use integrated caching from actions/setup-go@v3
* Pull Go version from go.mod
In general this should make life easier to external contributors, while ensuring latest changes in main branch get an image pushed to docker hub.
> Updates workflows to support external PRs

- db.go
This PR adds an `fsync()` after the final page of a WAL transaction is committed. This is because `PRAGMA synchronous=normal` can cause the SQLite WAL and the LTX database checksum to get out of sync as `NORMAL` mode allows for a window of data loss on shutdown.
> Force WAL fsync()

- fuse/wal_node.go
This code was copied over to SHM (where it belongs) but was not deleted from the WAL node.
> Remove dead code for WAL locking

- db.go
- fuse/database_node.go
- fuse/file_system.go
- fuse/shm_node.go
This pull request consolidates the `DatabaseGuardSet` & `WALGuardSet` into a single set of guards for the database. Database & SHM files can use the `UnlockDatabase()` and `UnlockSHM()` methods, respectively, to unlock the correct locks on flush.
> Consolidate locks & guards

- cmd/litefs/main_test.go
- db.go
- http/server.go
This pull request fixes the `DB.WriteSnapshotTo()` method to include the latest pages from the WAL file for the current position. Previously, this method only copied the database file which didn't include up-to-date pages.
Fixes #128
> Fix snapshot in WAL mode

- db.go
- http/server.go
- store.go
This pull request removes the `send frame`, `recv frame` and retention log lines as they were excessive under load. Periodic summary logging (e.g. every 10s) can be added in the future if it's helpful.
Fixes https://github.com/superfly/litefs/issues/141
> Reduce logging

- db.go
- store.go
The following code block
```go
f, err := os.Open(dirname)
if err != nil {
return err
}
defer f.Close()
fis, err := f.Readdir(-1)
```
can be replaced with just `os.ReadDir(dirname)`.
> refactor: replace `Readdir(-1)` with `os.ReadDir`

- db.go
Previously, replicas would only lock `WAL_READ0_LOCK` when applying changes because they always checkpointed. However, it looks like all read locks need to be acquired to avoid a `malformed database` error in the client.
Fixes https://github.com/superfly/litefs/issues/142
> Fix locking when applying LTX file to replica in WAL mode

- fuse/database_node.go
- fuse/journal_node.go
- fuse/root_node.go
- fuse/shm_node.go
- fuse/wal_node.go
This pull request adds the `fuse.OpenKeepCache` flag to `Open()` and `Create()` calls in the FUSE layer so that the OS page cache is preserved.
> Retain OS page cache on open(2)

- fuse/file_system.go
This pull request adds a `fuse.Unmount()` before attempting to mount. This helps avoid needing the user to run `umount` if there was an unclean exit of `litefs`.
> Attempt unmount for unclean exit

- db.go
- store.go
This PR fixes the `/debug/vars` output to include SHM locks. Previously, it only included the database locks (`PENDING`, `SHARED`, & `RESERVED`). This also moves the locks to a `locks` JSON map.
> Add SHM locks to /debug/vars

- cmd/litefs/main.go
- fuse/file_system.go
- fuse/file_system_test.go
- fuse/fuse.go
- http/server.go
- store.go
This pull request adds a set of endpoints on `/sys/debug` to update whether "debug" FUSE logging is enabled:
```sh
$ curl localhost:20202/sys/debug
```
```sh
$ curl -X PUT localhost:20202/sys/debug
```
```sh
$ curl -X DELETE localhost:20202/sys/debug
```
> Add endpoint for dynamically setting debug logging

- Makefile
- cmd/litefs/main_test.go
- http/http.go
- http/server.go
- store.go
This pull request fixes recovery in 3 scenarios:
1. Client has same TXID, mismatched checksum
2. Client has higher TXID than server
3. Client's TXID is lower than server, but preapply checksum does not match
All these scenarios are caused by unreplicated transactions from an old primary that has lost its primary status and is reconnecting as a replica. Different scenarios are caused by the number of unreplicated transactions and the number of new transactions on the new primary. LiteFS currently only supports asynchronous replication so unreplicated transactions will be lost in the event of a primary change.
> Fix recovery on replication position mismatch

- cmd/litefs/main.go
This pull request removes the sleep that occurs before executing the `exec` command. It should have been removed after the "ready state" was introduced in https://github.com/superfly/litefs/pull/100 but it was missed.
> Remove pre-exec sleep

- db.go
This PR fixes a bug where reopening a database would cause the `DB.mode` to be lost until another transaction occurred. During this time, locking was not done correctly and could result in a deadlock. Tested that this fix resolves the issue on a live cluster.
> Initialize DB.mode on open

- .github/workflows/push.yml
- cmd/litefs/main_test.go
- db.go
- fuse/file_system_test.go
- fuse/journal_node.go
Related to https://github.com/superfly/litefs/issues/166 & https://github.com/superfly/litefs/issues/167
> Add support for PERSIST journal mode

- fuse/file_system_test.go
- fuse/root_node.go
Previously, I was concerned about there being too many extra files and it'd be confusing for users so I excluded the `-pos` file from the `readdir` output. However, it's more confusing if folks are looking for it and can't find it so I'm adding it back in.
Fixes https://github.com/superfly/litefs/issues/174
> Show position file in readdir output

- consul/consul.go
Since LiteFS has a recovery mechanism for divergent primaries, this PR reduces the lock delay from 5 seconds to 1 second.
> Reduce Consul lock delay

- cmd/litefs/main.go
- fuse/file_system.go
There seems to be a deadlock on the `rio` lock used in `fuse.Conn.Close()` and `fuse.Conn.ReadRequest()`. If the connection is actively being read then it is unable to be closed. This prevents the LiteFS store from closing and releasing the primary lease. The Fly.io supervisor will then eventually hard kill the process which will then incur the Consul TTL which causes more downtime than it should.
This pull request simply removes the `fuse.Conn.Close()` as the connection will be closed by the process exit anyway.
Fixes https://github.com/superfly/litefs/issues/171
> Fix FUSE connection close deadlock

- http/server.go
- litefs.go
- store.go
This pull request adds an `END` frame to the stream so that the HTTP server can flush an end-of-stream indicator to the client. Helps with https://github.com/superfly/litefs/issues/182
> Add END frame to HTTP stream

- cmd/litefs/main.go
- cmd/litefs/mount.go
- cmd/litefs/mount_test.go
This PR changes invocation from:
```sh
$ litefs
```
to
```sh
$ litefs mount
```
This was changed in order to allow additional functions to be added in the future. Specifying no command will display a help screen listing the commands. There is also a `litefs version` command to print the current version of the binary.
> Move functionality to 'mount' subcommand

- db.go
- fuse/database_node.go
- fuse/journal_node.go
- fuse/shm_node.go
- fuse/wal_node.go
- internal/testingutil/testingutil.go
Fixes a bug in the checksum calculation for `VACUUM` in WAL mode too.
> Implement StrictVerify for WAL

- cmd/litefs/main.go
This adds the `strict-verify` flag to the YAML config. This is only meant to be used for testing & debugging as it's computationally expensive to run on anything but small databases. On every commit, it checksums the entire database and verifies that the checksum matches the `PostApplyChecksum` in the LTX transaction file.
> Add 'strict-verify' to YAML config

- cmd/litefs/main.go
- cmd/litefs/mount_darwin.go
- cmd/litefs/mount_linux.go
While Darwin (macOS) is not supported on LiteFS, this PR makes so that the binary will at least compile and return an error when `litefs mount` is run. Additional debugging tools will be added to the `litefs` binary and it'd be useful to be able to run those from macOS.
> Fix compilation on Darwin

- store.go
This PR changes `EnforceRetention()` to be skipped if retention duration is zero or less.
This can be set via the `litefs.yml` config:
```yml
retention:
duration: "0s"
```
This feature is only meant for testing & debugging. Retention should always be enforced in production. If it isn't, then disks can fill with LTX files as they will never be deleted.
> Allow retention enforcement to be disabled

- db.go
- internal/internal.go
- internal/internal_test.go
This PR fixes a bug where journals are not recovered correctly if the journal header has not been sync'd and the frame count field is zero.
> Fix frame count calculation on journal recovery

- go.mod
- go.sum
Adds fix from `ltx.ChecksumReader()` for empty file checksums (https://github.com/superfly/ltx/pull/18).
> Upgrade to LTX v0.2.7

- db.go
This PR ignores dirty page tracking when in WAL mode. This is only needed for rollback journal modes (`DELETE`, `PERSIST`, `TRUNCATE`) since pages are overwritten in-place. The WAL, however, appends pages so it's easy to determine the change set.
We may be able to calculate dirty pages at commit time for those rollback journal modes but that's for a separate PR.
> Skip dirty page tracking in WAL mode

- cmd/litefs/mount_linux.go
This pull request adds a `-debug` flag to the `mount` command that will override the `litefs.yml` config setting. This is useful for local testing & debugging where flipping the `debug` flag in the config is kind of annoying.
> Add -debug CLI flag to mount command

- db.go
- fuse/shm_node.go
- go.mod
- go.sum
- litefs.go
This pull request fixes a bug where the WAL segment is computed before the transaction fully completes. This can occur because SQLite can rewrite sections of the WAL as needed and then rewrites frame headers at the end. This can cause the database & the LTX files to become out of sync and cause `checksum mismatch` errors.
LiteFS now waits for `WAL_WRITE_LOCK` to be released before computing the transaction's pages. This ensures that the final version of the frames are written before determining the transaction boundaries.
> Move WAL commit to after WAL_WRITE_LOCK release

- db.go
- store.go
This pull request fixes a deadlock that occurs between `litefs.DB.mu` and the FUSE file system invalidation. Currently, the FUSE library is set to be synchronous so holding the `litefs.DB.mu` lock while committing to the journal and reading the `-pos` file can cause a deadlock.
The fix is to remove the `sync.Mutex` from `litefs.DB` as it was no longer necessary because SQLite obtains locks for all the calls inside that alter data. The `litefs.DB.pos` field has been converted to an `atomic.Value` so that its value can be obtained independently of the SQLite locks. This is useful as a write transaction on the rollback journal would prevent inspection of the position.
Originally reported by @kentcdodds in this Fly.io community forum post: …
> Fix Pos() deadlock with file system invalidation

- db.go
- go.mod
- go.sum
This pull request adds `litefs_db_latency_seconds` to the Prometheus metrics available at `GET /metrics`. This time is calculated using the timestamp saved to the LTX file on the primary node and subtracting it from the current time on the replica. Timestamps have millisecond precision.
This latency time can look off if there is significant clock skew between nodes or if a replica restarts and is catching up.
**This is basic monitoring purposes only.**
> Add latency metrics

- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
This config field will cause the `litefs mount` to not wait for the node to sync to the cluster before starting the `exec` child process.
> Add `skip-sync` config flag

- cmd/litefs/import.go
- cmd/litefs/import_test.go
- cmd/litefs/main.go
- db.go
- fuse/file_system.go
- http/client.go
- http/server.go
- litefs.go
This pull request adds a `litefs import` command to replace a live SQLite database on a LiteFS primary node. Existing SQLite connections should continue to operate normally.
Import to the local node:
```sh
$ litefs import -name my.db /path/to/db
```
Import to a remote node:
```sh
$ litefs import -url http://ord.myapp.internal:20202 -name my.db /path/to/db
```
> Add 'import' command

- .github/workflows/push.yml
This pull request sets `fail-fast` to `false` so CI doesn't stop other jobs in the matrix on one error.
> Disable fail-fast on CI

- db.go
- db_test.go
- fuse/database_node.go
- fuse/root_node.go
This is a minor PR to move functionality from the FUSE layer into a more well-defined API on the `litefs.DB`. This PR only handles the database file functionality for the most part. Journal, WAL, & SHM will be done in a separate PR. This should help with adding trace logging around higher level state in the future.
> Make FUSE layer thinner

- db.go
- litefs.go
This fixes missing checksum validation on the journal file. This primarily affects the `PERSIST` journal mode and recovery from a hard crash. This is because the `PERSIST` mode will leave journal entries at the end and expect the checksum to fail based on the new nonce at the journal header.
> Fix journal checksum validation

- cmd/litefs/main_test.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- db.go
- fuse/fuse_test.go
- litefs.go
This pull request adds trace logging at the logical database level instead of at the FUSE level. This can be enabled on the `./fuse` & `./cmd/litefs` tests and on `litefs mount` by specifying the `-tracing` flag. This has been added to help with #217.
> Add trace logging

- cmd/litefs/mount_test.go
- db.go
- fuse/file_system_test.go
- internal/testingutil/testingutil.go
This pull request moves around some of the LTX validation on startup so that we can extract the "WAL" fields from the last LTX header. If this header's WAL salt fields match an existing on-disk WAL file and the LTX's WAL offset + size and less than the on-disk WAL file, then we'll truncate the on-disk WAL file to match the LTX file.
This avoids a condition where a WAL file could sync ahead of the LTX file during a hard shutdown. When this occurs, the checksums would no longer match between the last LTX file and the on-disk database on startup.
> Sync WAL to LTX on startup

- db.go
- fuse/file_system_test.go
- litefs.go
Previously, the checksum was invalidated on the SHM when an LTX file was applied to a replica. This typically caused the SQLite client to rebuild the file on its own. However, in some cases, that wasn't happening properly.
This PR changes it so that LiteFS itself rebuilds the SHM header. This allows it to properly inject the correct page count and should improve performance slightly.
> Rewrite SHM after replica LTX apply

- .github/workflows/push.yml
- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/main_test.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- fuse/file_system.go
- fuse/file_system_test.go
- fuse/fuse_test.go
- http/server.go
- store.go
This pull request moves the `debug` flag into the new `fuse` section of the config. This was typically used for low-level debugging so this doesn't affect most people.
The new config syntax is:
```yml
fuse:
debug: true
```
The CLI flag on `litefs mount` has also been changed from `-debug` to `-fuse.debug`.
> Move debug flag to FUSE config section

- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- go.mod
- go.sum
This pull request changes the "trace log" so that it can be written to disk and the logs will automatically be rolled. Trace logging can produce A LOT of data quickly but we typically only care about very recent logs when an issue occurs.
The existing `-tracing` flag still works and can be used to enable the trace log via STDOUT. There is also a new `tracing` config section for enabling the trace log printing to disk:
```yml
tracing:
path: "/path/to/trace.log"
max-size: 64
max-count: 10
compress: true
```
This default configuration will produce a file called `/path/to/trace.log` and once that log reaches 64MB then it will be rolled over to a new file with a time-based name (e.g. `/path/to/trace.2022-12-15T14-11-07.991.log.gz`). Once 10 logs files have been produced, the oldest one will be …
> Implement rolling trace log

- .github/workflows/push.yml
- db.go
- fuse/file_system_test.go
- fuse/fuse_test.go
- litefs.go
This pull request changes the checksumming to skip the lock page since it is not written to. This page is `262145` on databases with the default 4KB pages.
> Skip lock page on checksum

- db.go
- go.mod
- go.sum
- litefs.go
This pull request also upgrades to LTX v0.2.11 which disallows encoding of lock pages.
> Skip lock page on snapshot

- cmd/litefs-bench/main.go
- cmd/litefs/main.go
- cmd/litefs/main_test.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- consul/consul.go
- db.go
- fuse/file_system.go
- fuse/file_system_test.go
- fuse/fuse_test.go
- http/server.go
- internal/testingutil/testingutil.go
- litefs.go
- store.go
This pull request fixes a bug when a node loses primary status, moves to a replica, and then performs a recovery. The on-disk WAL may no longer be in sync with the LTX files and can corrupt the database. This primarily affects WAL mode, however, it can in affect the rollback journal in edge cases as well.
> Checkpoint on primary/replica state change

- .github/workflows/push.yml
This PR removes the `-fuse.debug` flag from GitHub Actions CI builds. This flag generates a LOT of logs and Actions doesn't handle that load well. If a test does fail then we can test it locally with the flag enabled for more details.
> Remove FUSE debugging on CI testing

- cmd/litefs/mount_test.go
- db.go
- fuse/file_system_test.go
- internal/testingutil/testingutil.go
This pull request fixes a bug where a partial database file can prevent LiteFS from opening. This can be caused when a replica receives an LTX file that grows the database and the server is shutdown while applying the file. Page numbers are written in order so page 1 (which contains the database header) is written first and contains the database size. However, this doesn't match the actual size of the database since the end of the LTX file had not been written yet.
If an early EOF occurs on startup, LiteFS will now report `"database checksum ending early`" in the log and it will continue to reapply the last LTX file. On success, the database should now be valid and checksums should match.
> Continue init on database early EOF

- store.go
This pull request changes the default LTX retention from 1 minute to 10 minutes. Many deploys can take over a minute—especially if there is a large database and it needs to be checksummed and validated. In these cases, the retention could elapse and require a new snapshot which is expensive.
Small or medium-sized databases with a high write load may want to reduce this to avoid the storage cost of LTX files but this should be partly mitigated with LTX compression (https://github.com/superfly/litefs/issues/132).
Size-based retention is another approach that should be implemented in the near future as well.
> Increase default retention

- cmd/litefs/mount_linux.go
- consul/consul.go
This pull request removes the default Consul key as it is too easy to accidentally connect 2 clusters together if you're using the same Consul. This can have some very unexpected results.
Now, users will need to explicitly state the key they want to use for the cluster:
```yml
consul:
url: "${FLY_CONSUL_URL}"
key: "litefs/${FLY_APP_NAME}"
advertise-url: "http://${HOSTNAME}.vm.${FLY_APP_NAME}.internal:20202"
```
Previously, the key was `"litefs/primary"` but it can be any value that is unique to your cluster (e.g. `"production"`, `"staging"`, etc). On Fly.io, Consul usage is scoped to an organization so it only need to be a unique key within your org.
> Require explicit Consul key

- db.go
- fuse/shm_node.go
This pull request fixes an issue where an application shutdown that occurs after the last WAL write but before an explicit call to `Unlock(WRITE)` will cause the write to not be committed to LTX.
> Commit WAL on Handle Close

- cmd/litefs/etc/litefs.yml
- cmd/litefs/import_test.go
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
This pull request moves the `mount-dir` config option to a `fuse` subsection and renames it to `dir`.
So the previous config of:
```yml
mount-dir: /path/to/mnt
```
will now be:
```yml
fuse:
dir: /path/to/mnt
```
I'm also going to change the suggested value in documentation to `/litefs` so it's easy to remember. People tend to get confused by the data and mount directory. I'm going to change the `data-dir` to `/var/lib/litefs` to make it less memorable. :) 
Related to https://github.com/superfly/litefs/issues/164
> Move mount directory to FUSE config

- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- store.go
This pull request moves `data-dir` to `data.dir` and consolidates the `retention` fields into the `data` section as well.
If your config looked like this before:
```yml
data-dir: "/var/lib/litefs"
retention:
duration: "10m"
monitor-interval: "1m"
```
then it should now look like this:
```yml
data:
dir: "/var/lib/litefs"
retention: "10m"
retention-monitor-interval: "1m"
```
> Move data-dir to data section

- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
This pull request does the following:
1. Adds a `type` field to the `lease` section of the config.
2. Moves the common `hostname` and `advertise-url` fields from consul & static configs into the `lease` config. 
3. Moves the remaining fields in the `consul` section to the `lease.consul` section.
4. Moves the remaining fields in the `static` section to the `lease.static` section.
See `cmd/litefs/etc/litefs.yml` for an example of the layout.
> Consolidate consul & static lease configs

- .github/workflows/docker_image.yml
This pull request adds `ref_name` to the Docker builds if it is not a release build. This makes it easier to track what branch the build is from.
> Add ref_name to Docker builds

- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
This pull request removes the `lease.static.primary` field in favor of the `lease.candidate` field. The fields were similar enough in functionality that they could be merged.
So if your config was:
```yml
lease:
type: "static"
static:
primary: true
```
then you should change it to:
```yml
lease:
type: "static"
candidate: true
```
The `candidate` field should be `true` for the primary and `false` for replicas.
> Remove static.primary config field

- cmd/litefs/etc/litefs.yml
This pull request reformats the comments so they stay within a 65-character page width. This makes it easy to copy over to the docs page for reference and have minimal horizontal scroll.
> Refactor config comments

- .github/workflows/push.yml
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- db.go
- fuse/file_system_test.go
- go.mod
- go.sum
- http/server.go
- internal/chunk/chunk.go
- internal/chunk/chunk_test.go
- internal/testingutil/testingutil.go
- litefs.go
- litefs_test.go
- store.go
- store_test.go
This pull request upgrades to [LTX v0.3.0](https://github.com/superfly/ltx/releases/tag/v0.3.0).
To support this, LiteFS' stream format had to be changed in a **backwards incompatible** way. The body of the LTX stream frame is now implemented as a chunked byte stream. This was needed as we won't always know the size of the LTX file beforehand since LTX files can be compacted together. See the implementation in `internal/chunk` for more details.
> Implement LZ4 compression

- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- fuse/file_system.go
This pull request adds a `fuse.allow-other` option to the `litefs.yml` config file to allow non-root users to access the FUSE mount. To enable this, set the flag to `true` and also add a `user_allow_other` option `/etc/fuse.conf`.
Fixes #250 
```
user_allow_other
```
> Add allow_other FUSE mount option

- cmd/litefs/etc/litefs.yml
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- http/http.go
- http/http_test.go
- http/proxy_server.go
This pull request allows users to configure the proxy to ignore certain URL paths. The pattern format only allows an asterisk as a wildcard. For example, `/assets/*` would match all URLs with a `/assets/` path prefix. It would not, however, match `/assets`. This can be used for matching suffixes (e.g. `*.png`) and infixes (`*foo*`) as well.
Fixes #275 
The `litefs.yml` config file now has a `proxy.passthrough` field:
```yml
proxy:
addr:   ":8080"
target: "localhost:8081"
db:     "my.db"
passthrough: 
- "/debug*"
- "*.png"
```
or you can use the JSON array syntax:
```yml
proxy:
addr:   ":8080"
target: "localhost:8081"
db:     "my.db"
passthrough: ["/debug/*", "*.png"]
```
> Allow proxy passthrough list

- fuse/file_system.go
This fixes an issue where changing the database size invalidates all the pages from the OS page cache.
Fixes https://github.com/superfly/litefs/issues/149
> Enable FUSE ExplicitInvalidateData flag

- cmd/litefs-bench/main.go
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- db.go
- fuse/database_node.go
- fuse/file_system.go
- fuse/file_system_test.go
- fuse/fuse.go
- fuse/lock_node.go
- fuse/primary_node.go
- fuse/root_node.go
- fuse/shm_node.go
- go.mod
- go.sum
- http/client.go
- http/proxy_server.go
- http/server.go
- litefs.go
- litefs_test.go
- mock/client.go
- rwmutex.go
- store.go
- store_test.go
This pull request implements write forwarding ~~for WAL mode only~~. With write forwarding, any node can write to the database by borrowing the write lock from the primary, catching up, performing the transaction, and then shipping the changeset LTX file back to the primary. The transaction is then propagated out to the other replicas just like any other transaction.
Write forwarding is useful for infrequent writes and this should not be used for regular, write-heavy usage. The main use case for this is being able to run migration scripts from any node. This is useful because deployments can roll over nodes in an unexpected order so we want to run on the first node deployed regardless of its primary state.
Fixes #56 
Please note that the SQLite write lock is held for 1 round trip plus the …
> Implement HALT lock & write forwarding

- cmd/litefs/main.go
This pull request changes the startup behavior when there is an error and `exit-on-error` is `false`. Previously, the proxy server could have begun listening on the proxy port but the error could have occurred before the proxy had begun processing incoming requests. In this case, proxied requests would simply hang.
Now, the proxy server's listener is closed if there is a startup error so it is clear that the server is down. An alternative would have been to continue trying to start the proxy server but if there's a startup error then that the request would simply have errored in a different place.
Original post: https://github.com/superfly/litefs/pull/278#issuecomment-1419463845
> Stop proxy server on startup error

- cmd/litefs/export.go
- cmd/litefs/export_test.go
- cmd/litefs/main.go
- db.go
- http/client.go
- http/server.go
This pull request adds a `litefs export` command for downloading a point-in-time snapshot of the database. It is safe to use on a live cluster. This approach is significantly faster than using `VACUUM INTO` or `.backup` since it avoids any FUSE overhead.
```
$ litefs -name my.db /path/to/exported.db
```
```
$ litefs -url http://$HOSTNAME:20202 -name my.db /path/to/exported.db
```
> Add 'export' command

- cmd/litefs/mount_test.go
- fuse/journal_node.go
- fuse/root_node.go
- http/server.go
- litefs.go
- store.go
This pull request implements `Remove()` in the FUSE API so that databases can be deleted. This deletion also removes any associated files (`-journal`, `-wal, `-shm`, `-pos`, & `-lock`) and propagates the change down to the replica. The database can later be recreated but the position will restart from TXID 1.
Fixes https://github.com/superfly/litefs/issues/257
> Implement drop database

- cmd/litefs/main.go
- cmd/litefs/run.go
This pull request adds the `litefs run` command which executes a subcommand with certain guarantees from LiteFS. Currently, this is just used to acquire and release the `HALT` lock during execution but other options (such as promotion) may be done in the future.
Execute a `CREATE TABLE` while the local node holds the `HALT` lock. This enables write forwarding for migrations.
```sh
$ litefs run -with-halt-lock-on /litefs/db -- sqlite3 /litefs/db "CREATE TABLE t (x TEXT)"
```
> Add 'run' command

- db.go
- store.go
This pull request rolls back WAL changes if any error occurs in `CommitWAL()`. This is to ensure the WAL & LTX files are kept in sync. If the WAL cannot be truncated, the process must panic and it will fix itself on recovery after restart. This problem is particularly noticeable in write forwarding if the primary dies while a halt lock is held by a replica.
> Ensure WAL is truncated to original size on CommitWAL() failure

- cmd/litefs/mount_test.go
- consul/consul.go
- db.go
- http/server.go
- lease.go
- litefs.go
- mock/lease.go
- store.go
- store_test.go
This pull request implements the ability for a primary node to handoff its lease to a designated replica. The replica must be currently connected to the primary for this to work. After the lease ID is handed to the replica's stream, any error that occurs during handoff should cause the cluster to fall back to regular lease expiration handling.
The functionality is only implemented internally via the `litefs.Store.Handoff(nodeID)` function right now. Additional integration testing will be done once manual promotion (#299) is implemented in a separate PR.
Fixes #11
> Implement primary handoff

- cmd/litefs/mount_darwin.go
- http/proxy_server.go
As reported in https://github.com/superfly/litefs/pull/271#issuecomment-1500122333, the `__txid` cookie should be set on the `/` path.
> Set path for proxy server cookie

- cmd/litefs/config.go
- cmd/litefs/main.go
- cmd/litefs/mount_linux.go
- cmd/litefs/run.go
- http/client.go
- http/server.go
- litefs.go
This pull request adds flags to the `litefs run` command so that nodes can be promoted before running a scripts (e.g. migrations). It's probably useful to have a separate `litefs promote` command that doesn't run a subcommand but that can be done in a separate PR.
Fixes #299 
Attempt to promote, only on candidate nodes. This command will be a no-op if the node is not a candidate.
```sh
$ litefs run -promote -if-candidate -- rails db:migrate
```
Attempt to promote, but return an error code if the node is not a candidate:
```sh
$ litefs run -promote -- rails db:migrate
```
If you run with the `-if-candidate` flag and the node is not a candidate, you'll see a message in `STDERR` and no command will be run. It will return an error code of `0`:
```sh
$ litefs run -promote -if-candidate -- …
```
> Implement -promote & -if-candidate flags on run command

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
This pull request adds the ability to automatically promote a candidate node after it starts and syncs with the cluster. This is to improve the experience of deploying migrations by always allowing them to run on the local node.
If `lease.promote` is enabled on a node that is not a candidate, it is ignored and a log message is printed. 
```yml
lease:
promote: true
```
> Add 'promote' flag to config

- cmd/litefs/config.go
- cmd/litefs/config_test.go
- cmd/litefs/export_test.go
- cmd/litefs/import_test.go
- cmd/litefs/main_test.go
- cmd/litefs/mount_linux.go
- cmd/litefs/testdata/config/multi_exec.yml
- cmd/litefs/testdata/config/single_exec.yml
This pull request adds the ability to specify multiple subcommands in the config. This is useful with #306 as it allows a candidate node to promote itself, run migrations, and then run the application server. Commands are run sequentially. The last command is run asynchronously and its exit is sent to the `execCh`. If commands fail, then the LiteFS server will be shutdown.
This is an example of a config that only has candidates in a single region and automatically promotes when a new node starts up and syncs. Once promoted, a candidate node will run migrations and then start the app server. For non-candidate nodes, it will simply run the app server.
```yml
exec:
- cmd: "rails db:migrate"
if-candidate: true
- cmd: "rails server"
lease:
candidate: ${FLY_REGION == PRIMARY_REGION}
promote: …
```
> Allow multiple exec commands

- backup_client.go
- backup_client_test.go
- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- db.go
- http/client.go
- http/http.go
- http/proxy_server.go
- http/server.go
- litefs.go
- litefs_test.go
- liteserver/backup_client.go
- liteserver/backup_client_test.go
- mock/client.go
- store.go
- store_test.go
This is an initial implementation of the streaming backup client. This functions similarly to Litestream in that it pushes up changes periodically (currently every second). One big difference is that since LiteFS uses LTX for storage, multiple changes to the same page over that period can be compacted into a single page transferred.
Related to #18.
There are currently two implementations of `BackupClient`:
- `"file"` - this pushes to a directory on the local file system & is mainly used for testing.
- `"liteserver"` - this pushes to Liteserver which handles leveled compaction, snapshotting, & pushing to S3.
Originally, we were going to try to put S3 replication directly into LiteFS but it gets complicated since the primary is dynamic. We also have plans for allowing LiteFS to be run …
> Backup Client

- cmd/litefs/mount_test.go
This should help avoid a harmless timing issue on test shutdown.
> Fix CI error on close

- cmd/litefs-bench/main.go
- cmd/litefs/mount_test.go
- db.go
- fuse/file_system_test.go
- fuse/pos_node.go
- go.mod
- go.sum
- http/proxy_server.go
- http/server.go
- store.go
- store_test.go
This upgrades to LTX v0.3.2 and uses the new `ltx.TXID` to represent transaction IDs instead of `uint64`.
> Use ltx.TXID

- cmd/litefs/mount_darwin.go
- cmd/litefs/mount_test.go
- go.mod
- go.sum
- store.go
This pull request fixes the backup client so that it will start with a full snapshot if the remote backup server does not have a replication position for the database. This is needed when the initial LTX file has been removed because of retention enforcement.
> Initiate backup from snapshot

- backup_client.go
- backup_client_test.go
- cmd/litefs/mount_test.go
- db.go
- liteserver/backup_client.go
- liteserver/backup_client_test.go
- store.go
This pull request returns the high-water mark (HWM) returned from Liteserver during the `BackupClient.WriteTx()` API call and sets it on the `DB`. During retention enforcement, this high-water mark will be used to retain LTX files which have not made it to long-term storage. This ensures that LiteFS can sync up with Liteserver even when there is a catastrophic crash of the Liteserver disk.
Propagation of HWM to replica nodes will be done in a separate PR.
> Use HWM during retention enforcement

- client.go
- client_test.go
- cmd/litefs/mount_test.go
- http/server.go
- store.go
This pull request adds an `HWMStreamFrame` that allows the primary to propagate its local high-water mark for a database to all connected replicas. This will allow replicas to reclaim space from LTX files that have been persisted to long-term storage.
This is a naive implementation in that it only pushes out the HWM when a write transaction occurs. Every LTX stream frame will be followed by an HWM stream frame. There are edge cases that are not handled such as a large number of writes within a second followed by no writes. In those cases, the underlying LTX files will continue to persist on disk. However, those will be reclaimed once another write occurs and the HWM is propagated.
> Propagate high-water mark to replicas

- cmd/litefs/config.go
- cmd/litefs/main_test.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- db.go
- go.mod
- go.sum
- litefs.go
- store.go
This pull request handles divergence between the backup service and the LiteFS cluster. Because LiteFS does asynchronous replication, it's possible to have a primary node with unreplicated transactions that is disconnected the cluster and the rest of the cluster can diverge in a different transaction lineage.
Normally, this is handled by the new primary, however, there are instances where divergence can occur (e.g. primary loses role and later reacquires the primary status but transactions have been sent to the backup service). The backup service acts as a data authority so if LiteFS cannot determine a common transaction lineage, it must revert to the snapshot on the backup service.
There are four situations where divergence can occur:
1. New primary is empty and local database does not …
> Restore from backup when out-of-sync

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
This can be overridden in the `litefs.yml` file:
```yml
log:
timestamp: true
```
> Default slog to not print timestamp

- backup_client.go
- backup_client_test.go
- db.go
- go.mod
- go.sum
- store.go
This pull request fixes the LTX compactor used to send changes to the backup service so it respects the `data.compress` flag in the config.
> Compress LTX files sent to backup service

- client.go
- cmd/litefs/mount_test.go
- consul/consul.go
- fuse/file_system_test.go
- http/client.go
- http/server.go
- internal/internal.go
- internal/internal_test.go
- lease.go
- litefs.go
- mock/client.go
- mock/lease.go
- store.go
- store_test.go
This pull request adds a "Cluster ID" to LiteFS clusters. This ID is generated when the first node becomes primary and it is then sent as an HTTP header to each connected replica. Replicas without a cluster ID set will adopt the cluster ID of the primary they connect to.
This change ensures that two existing clusters cannot accidentally join one another and delete one of the cluster's data.
Fixes https://github.com/superfly/litefs/issues/331
> Implement cluster ID

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- internal/internal.go
- lfsc/backup_client.go
- lfsc/backup_client_test.go
This pull request automatically configures LiteFS Cloud when the `LITEFS_CLOUD_TOKEN` environment variable is set.
Fixes #334
> LiteFS Cloud environment variable

- lfsc/backup_client.go
url.Values is a map which needs to be initialized first before trying
to set a value.
> lfsc: fix nil pointer dereference

- cmd/litefs/mount_linux.go
- db.go
- fuse/file_system_test.go
- fuse/root_node.go
- fuse/shm_node.go
- lfsc/backup_client_test.go
- store.go
- store_test.go
This pull request changes the internal access of the SHM file to run through the FUSE mount to avoid timing issues with the mmap() access from SQLite.
Note: This is currently failing on `TestMultiNode_DropDB` because there's some kind of invalidation issue on the SHM file. 
Fixes #346
> Refactor SHM file access through FUSE

- db.go
- fuse/pos_node.go
This doesn't bother with the heartbeats from https://github.com/superfly/litefs/pull/340 and just sets the mtime on the pos file based on the timestamp from the latest ltx.
> Set mtime on pos file using timestamp from last ltx

- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- db.go
- fuse/file_system.go
- store.go
When the SHM access was changed to go through the FUSE mount (#346), this caused a race condition on FUSE shutdown for pending changes to the SHM. The FUSE connection is now explicitly closed and internal changes to SHM are sync'd to FUSE. There is also a "mount ready" flag on the store to indicate when the FUSE mount is available so that the store does not attempt to access it before mount or after unmount.
> Wait for SHM changes to flush before exit

- db.go
This pull request makes 2 optimizations to the checksum computation on each transaction:
1. Changes the checksum map to a slice. This should improve lookup performance.
2. Add a higher-level caching layer so that contiguous blocks of pages can be calculated once and reused.
This initial optimization only attempts to improve checksums being computed from the database file itself. If any pages in a block are in the WAL file, their cached block checksum is ignored and we recalculate the block by individual pages.
> Implement checksum cache

- cmd/litefs/mount_linux.go
- fly/environment.go
- litefs.go
- store.go
This pull request adds an `Environment` interface for interacting with the host environment and adds an implementation for Fly Machines although other environments can be added in the future.
Fixes #356
> Set host environment metadata

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- store.go
This pull request adds a "full sync" interval to the backup client so that it will recheck the position on the backup server periodically. This ensures that a cluster can be restored to an old state even in the absence of active writes on the database.
> Periodically check backup server for updates

- fly/environment.go
- litefs.go
- store.go
This pull request changes `Environment.SetPrimaryStatus()` so that it is non-blocking, it retries five times on failure, and it change some error messages to report `DEBUG` instead of `INFO`. The environment metadata is not critical to correctness so we can lower the error severity.
Fixes #363, #364
> Retry environment metadata updates

- http/proxy_server.go
When a non-GET/HEAD request hits the proxy, if there is no primary then the proxy still forwards the request to the target server. However, applications are not expecting to handle primary disconnection since it is delegated to the proxy so the proxy should just return a `503 Service Unavailable` error.
> Return 503 from proxy when no primary available

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
Currently, the trace log is enabled when `tracing.path` is set. However, it can be useful to selectively choose which node has tracing enabled.
This PR adds a `tracing.enabled` field which defaults to `true`. If it is `true` and the `tracing.path` is set then the trace log is enabled. This PR was tested manually.
```yml
tracing:
enabled: ${FLY_REGION == 'syd'}
path:    "/var/log/litefs/trace.log"
```
> Add 'enabled' flag to tracing config

- cmd/litefs/mount_linux.go
- db.go
- store.go
This pull request adds the `litefs_lag_seconds` gauge and returns the lag behind the primary in seconds. This metrics is server-wide as opposed to the per-db `litefs_db_latency_seconds` metric.
It also accounts for heartbeats so replicas that don't receive transactions for more than a second will still have their lag updated. When no transactions are received, a lag of ~1s is normal as that is the heartbeat interval.
The `litefs_db_latency_seconds` metric has been renamed to `litefs_db_lag_seconds` for consistency as well.
> Expose lag as prometheus metric

- cmd/litefs/mount_linux.go
This PR cleans up `Close()` errors that can cause tests to intermittently fail. These errors don't affect the function of the tests as they occur after shutdown.
> Fix close errors

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- http/proxy_server.go
This pull request adds a health check endpoint to the LiteFS proxy so that upstream proxies can temporarily remove the node if replication lag exceeds a threshold. This threshold defaults to `10s`.
The default threshold is 10 seconds but you can change it in the `proxy` section of the config:
```yml
proxy:
addr: ":8080"
target: "localhost:8081"
db: "my.db"
max-lag: "5s"
```
If you enable the `proxy.debug` flag then you'll also see debug messages when the proxy fails:
```
proxy: GET /litefs/healthz: current replication lag of 10.7s exceeds maximum threshold of 10s
```
If you are using Fly.io, see the [fly.toml health checks documentation](https://fly.io/docs/reference/configuration/#http_service-checks). Below is an example:
```
[[http_service.checks]]
grace_period = "10s"
interval = "30s" …
```
> Proxy health check

- http/proxy_server.go
The health check endpoint was previously `"/litefs/healthz"` which is borrowed from Kubernetes naming convention. However, this isn't Kubernetes so let's just call it `"/litefs/health"`. 
/cc @kentcdodds
> Rename health check endpoint

- .github/workflows/push.yml
- .github/workflows/release.yml
- Dockerfile
- Dockerfile.test
- go.mod
This pull request also upgrades [actions/setup-go](https://github.com/actions/setup-go) to v4.
> Upgrade to Go 1.21

- store.go
This pull request adds the cluster ID that Consul has already been initialized with so the user can reset it.
See related: https://community.fly.io/t/trying-to-bring-up-a-machine-after-deleting-its-volume/14806
> Report existing consul cluster ID

- backup_client_test.go
- client.go
- cmd/litefs/mount_test.go
- db.go
- fuse/root_node.go
- go.mod
- go.sum
- store.go
This pull request adds support for soft deleting databases. Previously, deleting a database would wipe it from the primary and then the primary would send a "drop db" frame to the replicas to have them delete as well.
However, this is problematic when connected to LiteFS Cloud (LFSC) for several reasons. First, LFSC acts as the data authority so when the primary removes the database, LiteFS detects that it exists on LFSC and downloads a snapshot, thus negating the delete. Second, LFSC aims to provide durability even in the face of accidental deletion so a delete should not remove old versions of the database.
Changes to LTX (https://github.com/superfly/ltx/pull/46) were made to have a zero-length database represent a deletion. These changes have been integrated into LFSC and this PR …
> Implement soft delete

- http/server.go
This pull request adds a `GET /debug/rand` endpoint to the internal LiteFS HTTP server. When connected, this endpoint will stream bytes from a PRNG until the client disconnects or a timeout of 1 minute is encountered.
The purpose of the endpoint is to help debug slowness on a replica to see if poor network conditions are the problem. 
Running `curl` against the endpoint will dump out performance metrics:
```sh
$ curl http://$PRIMARY:20202/debug/rand > /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 2685M    0 2685M    0     0   395M      0 --:--:--  0:00:06 --:--:--  401M
```
> Add /debug/rand endpoint

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- db.go
- http/server.go
This pull request adds a `snapshot-timeout` configuration to the HTTP server. This prevents slow LTX snapshot writes from holding locks on the database for an excessive period of time. If not specified, it defaults to the retention period since exceeding this period would require the replica to re-snapshot anyway.
```yml
http:
snapshot-timeout: "5m"
```
> Add snapshot timeout

- backup_client.go
- cmd/litefs/mount_test.go
- db.go
- store.go
- store_test.go
This pull request changes the node ID to be regenerated on startup instead of being persisted to disk. Persisted node IDs caused issues when a volume was cloned as two nodes would end up with the same ID and would not be able to connect to one another. This PR also removes the log prefix from all logging as it mostly cluttered the logs.
Fixes https://github.com/superfly/litefs/issues/361
> Make node ID ephemeral

- cmd/litefs/mount_test.go
- db.go
- go.sum
- http/server.go
- store.go
This pull request implements the `GET /events` endpoint which provides a newline-delimited stream of JSON objects. Currently, it implements 3 types of events: `init`, `tx`, & `primaryChange`.
/cc @tantaman
The `init` event is currently identical to the `primaryChange` event in that it shows information about this primary status. It is always the first event published.
```
{
"type": "init",
"data":
{
"isPrimary": true,
"hostname": "myPrimaryHost"
}
}
```
The `tx` event is published every time a new LTX is written by the node or is received and applied from the primary. 
```
{
"type": "tx",
"db": "db",
"data":
{
"txID": "0000000000000027",
"postApplyChecksum": "83b05248774ce767",
"pageSize": 4096,
"commit": 2,
"timestamp": "2023-09-06T19:12:34.985Z"
}
}
```
The `primaryChange` event shows …
> Add event stream

- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- db.go
- internal/system_os.go
- litefs.go
- mock/os.go
- store.go
Failures during the last commit phase of WAL operation need to exit as we currently don't have a way to communicate to the SQLite client to rollback the transaction. The commit is detected by the release of the `WRITE` lock, however, SQLite doesn't handle errors from this syscall so an exit is called instead.
We originally used the WAL write syscall to determine the transaction boundary, however, it is not contiguous when pages are rewritten within a single transaction so it make tracking boundaries inconsistent. We also evaluated checking the fsync syscall, however, this is not used if `PRAGMA synchronous=normal` is enabled by the client. In the long term, we should re-evaluate the use of `write(2)` to determine transactional boundaries in WAL mode.
> Exit on WAL commit failure

- client.go
- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- http/client.go
- http/server.go
- mock/client.go
- store.go
- store_test.go
As discussed in [this Community forum post](https://community.fly.io/t/litefs-multiple-databases/15595/6), this PR adds a config option to specify a subset of databases to be replicated to a specific replica. Please note that this config option is only allowed on non-candidate nodes! If we allowed it on candidate nodes then it would delete the other databases when the node became primary.
To use the filter, specify it with the `lease.databases` config field:
```yml
lease:
candidate: false  # Must not be a candidate, otherwise will error out on startup
databases: ["foo.db", "bar.db"]
```
or you can use the multiline array format:
```yml
lease:
databases: 
- "foo.db"
- "bar.db"
```
> Filter replicated databases

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- http/proxy_server.go
- store.go
This pull request changes the HTTP proxy so that it will wait until it has primary information before attempting to redirect. It will wait up to 5 seconds by default but this can be changed in the config.
Fixes https://github.com/superfly/litefs/issues/406
To change the primary redirect timeout, you can specify it in the `proxy` section of the config:
```yml
proxy:
addr: ":8080"
target: "localhost:8081"
db: "my.db"
primary-redirect-timeout: "10s"
```
> Proxy primary redirect timeout

- cmd/litefs/mount_test.go
- db.go
This pull request fixes a bug where the backup client attempts to read the database file for a deleted database and errors. Instead, it should generate a zero-length LTX file. 
See: https://community.fly.io/t/litefs-cloud-backups-failing/15729
> Fix snapshot generation of deleted database

- cmd/litefs/run.go
- http/server.go
- lease.go
- litefs.go
- mock/lease.go
This pull request makes a few changes to the `GET /info` endpoint:
- Renames `primary` to `isPrimary`
- Adds a `primary` object with a `hostname` field to show the current known primary node.
- Removes the `id` field
> Add primary hostname to /info endpoint

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- http/proxy_server.go
This pull request adds a proxy config setting to specify regex-matching paths to always forward to the primary (even when using `GET` & `HEAD` methods). This was proposed on [this Fly.io Community forum post](https://community.fly.io/t/litefs-http-proxy-failing-with-nextauth/15917/3).
```yaml
proxy:
always-forward:
- "^/my/path$"
- "^/my/other/path$"
```
> Add always-forward config to proxy server

- cmd/litefs/config.go
- cmd/litefs/mount_test.go
This pull request sets defaults for the `litefs.yml` as follows:
```yml
data:
dir: "/var/lib/litefs"
fuse:
dir: "/litefs"
```
> Default data dir & FUSE dir

- http/proxy_server.go
Fixes https://github.com/superfly/litefs/issues/415
> Implement flushing copy on proxy response

- cmd/litefs/config.go
- cmd/litefs/mount_linux.go
- http/proxy_server.go
This pull request adds several HTTP server timeout options to the `proxy` section of the config:
```yml
proxy:
read-timeout = "0s"
read-header-timeout = "10s"
write-timeout = "0s"
idle-timeout = "30s"
```
These correspond to the timeouts listed in the [http.Server](https://pkg.go.dev/net/http#Server) docs.
> Add proxy server timeout config options

- cmd/litefs/mount_test.go
- db.go
This pull request adds a check to ensure that an exclusive lock has been acquired for the `WRITE` lock byte when attempting to write to the WAL.
Fixes https://github.com/superfly/litefs/issues/425
> Prevent WAL writes when using EXCLUSIVE locking mode

- cmd/litefs/mount_linux.go
This PR adds support for redirecting the LiteFS Cloud backup client to another api-compatible endpoint.
> Support overridding the default LiteFS Cloud endpoint

- .github/workflows/push.yml
- cmd/litefs/export_test.go
- cmd/litefs/import_test.go
- cmd/litefs/mount_linux.go
- cmd/litefs/mount_test.go
- db.go
- go.mod
- go.sum
~I wanted to make sure we like the new API before merging https://github.com/superfly/ltx/pull/56, so this PR targets that branch currently. If we're happy with how this PR looks, I'll merge the ltx one and rebase this one.~
Update: I merged and cut a new release for https://github.com/superfly/ltx/pull/56. I rebased this branch, so it should be ready to go.
> Use optimized checksumming when loading database

- .github/workflows/docker_image.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- Dockerfile
- cmd/litefs/mount_linux.go
- fuse/file_system.go
- fuse/file_system_test.go
This PR adds support for using the LiteFS container as a sidecar, when used in a container runtime that supports mount propagation (e.g. filesystems mounted inside one container can be propagated to the host or other containers).
- It adds the required `fusermount3` binary
- It adds a `-skip-unmount` argument to `litefs mount`, and uses that as the container command. When mounting on top of an existing mountpoint, LiteFS would unconditionally unmount it. This would break mount propagation, so we want to avoid this behavior.
Fixes https://github.com/superfly/litefs/issues/365
> Dockerfile: Add sidecar support
