superfly/litefs

db.go
go.mod
go.sum

This pull request upgrades to LTX v0.2.0 which changes the file format to better support streaming. More details can be found in the relevant LTX PR (https://github.com/superfly/ltx/pull/3).

Upgrade to LTX v0.2.0

---

cmd/litefs/main_test.go
db.go
litefs.go

Support non-default page size

---

consul/consul.go

This pull request automatically registers a Consul node to represent all LiteFS instances in a cluster when a key prefix is used. The key prefix can be used in a multi-tenant Consul environment to restrict nodes by ACL. Consul sessions require a node when using an ACL.
Fixes #62

Optional registration of Consul node

---

cmd/litefs/main.go

This pull request removes the need to specify the `consul.advertise-url` and defaults the value to use `http://${HOSTNAME}:${PORT}`

Default Advertise URL

---

cmd/litefs/main_test.go
db.go

This pull request adds verification of the database state on startup. It computes the checksum of the current `database` file and ensures it matches the post-apply checksum of the latest LTX file. If the two checksums do not match, the startup fails. 
Eventually this should be handled more gracefully so that the node simply does not become primary and resnapshots from another node.

Verify database checksum on startup

---

.github/workflows/fun.yml
cmd/litefs/main_test.go

This pull request adds an initial cut of a long-running, functional test. It's currently testing a primary with a single replica and it does not test failover yet.

Add long-running, functional test

---

store.go

This removes the check during an stream's LTX frame processing that ensures the current checksum matches the previous checksum if the LTX is sending a new snapshot. This is because the snapshot will overwrite all data.

Skip LTX checksum check on snapshot

---

db.go
fuse/database_node.go
rwmutex.go
rwmutex_test.go

This pull request changes `litefs.RWMutex` so that the caller can only operate on it by using a guard. This simplifies a lot of code that would check both the "has guard" and "has no guard" cases.

Refactor RWMutex & RWMutexGuard

---

store.go

Signed-off-by: Ryan Russell <git@ryanrussell.org>
Small fix-up in disconnected message

docs: `disconnected` fixup in store

---

cmd/litefs/main.go

This PR adds an `exit-on-error` config option. When true, the process will exit when an error occurs on startup. When false, the process will hang until a SIGINT is received. Defaults to true.
Fixes https://github.com/superfly/litefs/issues/136

Continue running on error

---

db.go
fuse/file_system_test.go

This pull request fixes an issue where `litefs` can have a mismatch between the database state and the last LTX checksum when LiteFS is shutdown midway through a journal transaction that has flushed pages to disk. Instead of relying on SQLite to rollback the journal, this PR performs the rollback within LiteFS so it can correctly compute the checksum on startup.
Fixes https://github.com/superfly/litefs/issues/134

Rollback journal on startup

---

cmd/litefs/main.go
cmd/litefs/main_test.go

Fixes https://github.com/superfly/litefs/issues/135

Validate that mount & data directories are different

---

cmd/litefs/main.go

This pull request allows users to override the `exec` configuration value in the CLI arguments by specifying a double dash (`--`) followed by the exec args.
Fixes https://github.com/superfly/litefs/issues/133
```
$ litefs -config /path/to/lite.yml
```
```
$ litefs -config /path/to/lite.yml -- myapp -addr :3000
```
```
$ litefs -config /path/to/lite.yml --
```

Specify 'exec' command from CLI

---

cmd/litefs/main_test.go
db.go

This pull request fixes an issue where a transaction that fails between the LTX commit & the journal/WAL commit will place the database in a state on the prior commit. This will cause the LTX checksum to not match and it will fail on startup. Now, `litefs` will replay the last LTX file to ensure the database contents match after this failure scenario.

Replay last LTX on recovery

---

cmd/litefs/main_test.go
store.go

This pull request removes other LTX files for a database when a snapshot is received. A snapshot can occur when a replica reconnects to the primary and has either lagged too far behind or it has diverged. A snapshot contains all pages in the database so the other LTX files are no longer necessary.

Clear LTX files on snapshot received

---

.github/workflows/push.yml
cmd/litefs/main_test.go
fuse/file_system_test.go
fuse/journal_node.go

Related to https://github.com/superfly/litefs/issues/166 & https://github.com/superfly/litefs/issues/167

Add support for TRUNCATE journal mode

---

cmd/litefs/main.go
cmd/litefs/main_test.go

Implements the grammar defined in https://github.com/superfly/litefs/issues/176.

Allow simple expressions in env var expansion

---

db.go
http/server.go

This adds some additional logging around snapshot TXIDs. It also rewords the "resetting to snapshot" since that sounds scarier than it actually is.
Helps with https://github.com/superfly/litefs/issues/173

Improve snapshot logging

---

.github/workflows/push.yml
cmd/litefs-bench/main.go

This is an initial cut of simple program for load testing single-node LiteFS.

Add litefs-bench test program

---

cmd/litefs-bench/main.go
db.go

This PR fixes a bug where recovery did not properly check for journal magic on headers after the first segment.

Check for journal header magic after first segment

---

db.go
fuse/file_system_test.go

This pull request fixes a `concurrent map iteration and map write` bug caused by iterating over the `litefs.DB.wal.frameOffsets` during a snapshot. This function operates with shared locks, however, in WAL mode writes can still occur while reads are happening. To fix the issue, an exclusive lock on `WAL_WRITE_LOCK` is made briefly during the frame offsets copy and then it reverts back to shared locks for the remainder of the snapshot.
/cc @dangra

Fix WriteSnapshotTo() lock in WAL mode

---

db.go
db_test.go
fuse/database_node.go
fuse/file_system.go
fuse/journal_node.go
fuse/shm_node.go
fuse/wal_node.go

This is a continuation of the consolidation work in https://github.com/superfly/litefs/pull/215 but also includes the journal, SHM & WAL. This is in preparation for #217.

Consolidate Remaining DB API

---

db.go

This is a temporary fix for preventing passive checkpoints during a WAL commit. LiteFS works by rebuilding a WAL transaction as an LTX file at the end of a commit. These can be out of sync in the event of a failure but LiteFS will truncate the WAL to match the LTX file's position in this case.
However, there is a still a race condition:
1. A WAL segment is committed by the SQLite client.
2. Another SQLite client to perform a `PASSIVE` checkpoint and copies the segment into the database.
3. The `litefs` process is killed before the LTX file is written.
4. On recovery, the WAL is truncated to match the LTX but the truncated WAL pages have already been copied over.
5. A checksum mismatch is reported on startup.
This pull request now requires that the owner that is acquiring the `CKPT` lock …

Implicit CKPT lock on WRITE lock

---

db.go

This pull request adds a safeguard so that the WAL is not accidentally rewound after LiteFS has processed the frames. A partial rewind can corrupt the database as LiteFS and SQLite will get out of sync.

Prevent partial WAL rewind

---

cmd/litefs/main.go
cmd/litefs/mount_linux.go
cmd/litefs/mount_test.go

Setting an invalid field will now be reported as an error.

Strict config type checking

---

cmd/litefs/mount_test.go

There was an issue with v0.2.0 where failing on the initial database creation transaction resulted in issues on restart. This test backfills a test for the fix.

Add test for rollback on database creation

---

db.go

In the long-running test cluster, there was a panic on a `concurrent map read and map write` while the SHM was being unlocked and the DB write request were in-flight from FUSE. This pull request wraps the map in a mutex.
```
2022-12-29T12:30:47Z app[f6f8f4aa] lhr [info]fatal error: concurrent map read and map write
2022-12-29T12:30:47Z app[f6f8f4aa] lhr [info]goroutine 186696 [running]:
2022-12-29T12:30:47Z app[f6f8f4aa] lhr [info]	ithub.com/superfly/litefs.(*DB).pageChecksum(...)
2022-12-29T12:30:47Z app[f6f8f4aa] lhr [info]github.com/superfly/lit
2022-12-29T12:30:47Z app[f6f8f4aa] lhr [info]	/src/litefs/db.goy/lit
fs.(*DB).CommitWAL(0xc0000a0480, {0xb96ad0?, 0xc002777800?})
2022-12-29T12:30:47Z app[f6f8f4aa] lhr [info]	/src/litefs/db.go:1275 +0x1125
2022-12-29T12:30:47Z app[f6f8f4aa] …
```

Add mutex to DB.chksums

---

cmd/litefs/main.go

Fixes https://github.com/superfly/litefs/issues/264
/cc @kentcdodds

Passthrough application exit code

---

internal/chunk/chunk.go
internal/chunk/chunk_test.go

Remove buffer size limit in chunked writer

---

db.go

This change came out of building the `HALT` lock (https://github.com/superfly/litefs/pull/277) but I'm pulling it out here so it doesn't get squashed to the same commit.

Use spin lock for write lock acquisition

---

.github/workflows/docker_image.yml
.github/workflows/release.yml
http/http.go

Add armv6 & armv7 builds

---

http/proxy_server.go

proxy: treat HEAD requests as reads

---

cmd/litefs/mount_test.go
db.go
store.go

Fixes https://github.com/superfly/litefs/issues/339

Fix 'locking protocol' bug while streaming snapshot in progress

---

lfsc/backup_client.go

LFSC returns the ID of an instance that handles particular LiteFS
cluster in replies. Use it to ask fly-proxy to route to correct instance
right away and avoid additional round-trip.

lfsc: ask fly-proxy to route to correct node if we know it

---

cmd/litefs/mount_linux.go
cmd/litefs/mount_test.go
db.go
fuse/file_system.go
fuse/file_system_test.go
fuse/root_node.go
fuse/shm_node.go
lfsc/backup_client_test.go
store.go
store_test.go

This pull request reverts #348 & #351 as it caused issues where FUSE would lock up.

Revert SHM Refactor

---

fly/environment.go

This pull request changes the Fly Machines metadata to use the `"role"` key rather than the `"primary"` key.

Rename metadata field to 'role'

---

http/proxy_server.go

This pull request fixes an issue where the LiteFS HTTP proxy attempts to connect to the application server before the server has started up. To fix this, the `Dial` function on the proxy's transport now retries the connection every 100ms until the connection is successful or default dialer timeout (`30s`) elapses. It only retries on `ECONNREFUSED` so other disconnection errors are not retried.
Fixes https://github.com/superfly/litefs/issues/367

Retry proxy on connection refused error

---

cmd/litefs/mount_linux.go

This pull request changes the startup of the LiteFS HTTP proxy. Previously, the proxy port was opened immediately after the internal HTTP API server was opened but before the node was marked as "ready". For LiteFS, a node is ready when it connects and syncs to an existing primary node or if it becomes the primary node itself.
The proxy will still temporarily hold inbound requests until the application server starts up but this change will fix the situation where a node cannot connect to the primary but still accepts proxy connections.
1. Listen and serve on API port (`:20202`)
2. Listen on proxy port (user-defined).
3. Wait for ready state.
4. Optionally promote node if candidate.
5. Serve proxy requests.
6. Run `exec` commands.
1. Listen and serve on API port (`:20202`)
2. Wait for ready …

Delay proxy listen until marked ready

---

cmd/litefs/mount_test.go
consul/consul.go
http/server.go
lease.go
mock/lease.go
store.go

This pull request is meant to prevent a situation where two nodes can request a handoff at the same time and one will stall.

Add handoff timeout

---

db.go
fuse/pos_node.go
go.mod
go.sum
http/server.go
store.go

This pull request upgrades to LTX v0.3.13 to utilize the `ltx.Checksum` type.

Use ltx.Checksum type

---

store.go

This sets an upper bound on the number of LTX files to compact together at one time so that it doesn't exhaust the available file descriptors. It's currently hardcoded but may move to a configuration option if needed in the future.

Limit LTX compaction during backups

---

Dockerfile

See: https://github.com/golang/go/issues/64433

Upgrade to Go v1.21.5

---

docs/ARCHITECTURE.md

👋 
There were some other typos identified by `typos --check-filenames` and `codespell .` in the source code:
- NodeCreater -> NodeCreator
https://github.com/superfly/litefs/blob/63eab529dc3353e8d159e097ffc4caa7badb8cb3/fuse/root_node.go#L23
- implemenation -> implementation
https://github.com/superfly/litefs/blob/63eab529dc3353e8d159e097ffc4caa7badb8cb3/backup_client.go#L41
- attemping -> attempting
https://github.com/superfly/litefs/blob/63eab529dc3353e8d159e097ffc4caa7badb8cb3/consul/consul.go#L248)
- cancelation -> cancellation
https://github.com/superfly/litefs/blob/63eab529dc3353e8d159e097ffc4caa7badb8cb3/store_test.go#L287
- noes -> nodes
https://github.com/superfly/litefs/blob/63eab529dc3353e8d159e097ffc4caa7badb8cb3/tests/litefs.yml#L47
But they are not user-facing so I skipped …

typo: asychronous -> asynchronous
